### PR TITLE
npm love

### PR DESCRIPTION
**Pull request by claviska**
Because some folks just like wombats

### CODE REVIEW

**Review by KonnorRogers — APPROVED** [review]
I guess if we're using microsoft stuff, we should probably use npm...

**Comment by ParamagicDev** [comment]
Supporting both pkg managers is a pain. NPM will be default. If someone wants yarn, tell em to fork it!

**Comment by claviska** [comment]
You mean "npm"  🙃

**Comment by ParamagicDev** [comment]
I said what I said! NPM is default!

**Pull request closed without merging**
